### ISSUE TITLE
btc Hot-Wallet Balance show the coins but in btc fund does not 

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [pankaj9310/graviex-peatio#13]
I wondering why i can't see the btc wallets address in funds? but I can see the the full balance of the wallet in my hot wallet.

I am wondering what it is going on? what it is wrong? for sure the btc wallet it is connect, if it was not I could not be able to see my full balance of my wallet right?

what do you guys think can be? how can I debug this?

**bitcoind it is running, wallet sync and I can see my hotwallet ballance.** and i had included the right btc address.

thank you.

**Comment by pankaj9310** [comment]
I guess the daemons are not running and you require to add deposit address for the currency
pls check your daemons status using 
`bundle exec bundle exec rake daemons:status`

**Comment by openbooknoobdeveloper** [comment]
all the daemons are running and I inserted in the currencies the wallet address too.

I have no idea what it is going on, since I am not missing any step and doing all in the right way, 

I cloned this fork: https://github.com/InfraexDev/peatio/  and everything was working fine, generating address so I am wondering it is something missing on your fork? could u do a fresh install using your project?

thanks a lot for your help.
 
```

k.rb: running [pid 8229]
peatio:amqp:notification: running [pid 8238]
peatio:amqp:pusher:1: running [pid 8251]
payment_transaction.rb: running [pid 8261]
peatio:amqp:trade_executor:1: running [pid 8275]
peatio:amqp:order_processor:1: running [pid 8290]
stats.rb: running [pid 8299]
peatio:amqp:deposit_coin:1: running [pid 8314]
peatio:amqp:matching: running [pid 8325]
global_state.rb: running [pid 8339]
peatio:amqp:market_data: running [pid 8351]
peatio:amqp:deposit_coin_address:1: running [pid 8367]
dividend.rb: running [pid 8381]
hot_wallets.rb: running [pid 8397]
websocket_api.rb: running [pid 8426]
withdraw_audit.rb: running [pid 8466]
currencies_stats.rb: running [pid 8510]
peatio:amqp:withdraw_coin: running [pid 8523]
```

**Comment by openbooknoobdeveloper** [comment]
```
I, [2018-11-18T11:27:43.345032 #8367]  INFO -- : Received: Worker::DepositCoinAddress {"payment_address_id":2,"currency":"btc","locale":"en"}
I, [2018-11-18T11:27:43.360557 #8367]  INFO -- : Making class (btc)

F, [2018-11-18T11:27:43.360759 #8367] FATAL -- : wrong number of arguments (3 for 0) (ArgumentError)
/home/ubuntuuser/graviex-peatio/app/services/coin_rpc.rb:47:in `handle'
/home/ubuntuuser/graviex-peatio/app/services/coin_rpc.rb:44:in `method_missing'
/home/ubuntuuser/graviex-peatio/app/models/worker/deposit_coin_address.rb:17:in `process'
/home/ubuntuuser/graviex-peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2018-11-18T11:27:43.360824 #8367] FATAL -- : /home/ubuntuuser/graviex-peatio/app/services/coin_rpc.rb:47:in `handle'
/home/ubuntuuser/graviex-peatio/app/services/coin_rpc.rb:44:in `method_missing'
/home/ubuntuuser/graviex-peatio/app/models/worker/deposit_coin_address.rb:17:in `process'
/home/ubuntuuser/graviex-peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/ubuntuuser/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
```

**Comment by openbooknoobdeveloper** [comment]
@pankaj9310  do I need change this too?  in bitcoin.conf? 

# Notify when receiving coins
`    walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'`
