### ISSUE TITLE
NameError: uninitialized constant MailsViewer

### ISSUE THREAD

**Issue by LightBurdenOfficial** [pankaj9310/graviex-peatio#18]
> $ bundle exec rake assets:precompile
> 
> rake aborted!
> NameError: uninitialized constant MailsViewer
> /home/spero/peatio/config/routes.rb:15:in `block in <top (required)>'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:337:in `instance_exec'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:337:in `eval_block'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:315:in `draw'
> /home/spero/peatio/config/routes.rb:9:in `<top (required)>'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:40:in `each'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:40:in `load_paths'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:16:in `reload!'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:26:in `block in updater'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/activesupport-4.0.12/lib/active_support/file_update_checker.rb:75:in `execute'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:27:in `updater'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
> /home/spero/peatio/config/environment.rb:5:in `<top (required)>'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
> /home/spero/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
> /home/spero/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
> Tasks: TOP => environment
> (See full trace by running task with --trace)
>

**Comment by LightBurdenOfficial** [comment]
```
$ echo "export RAILS_ENV=production" >> ~/.bashrc
$ source ~/.bashrc
```

I do not know what happened to my system, but after running this command again, the error no longer appeared.

Reference for correction: https://github.com/pankaj9310/graviex-peatio/commit/b601684eeecebd1d59156f26cd0afad2b9bd25aa
